/* oxlint-disable react/only-export-components */
import React, { createContext, useContext, useState, useCallback } from "react";

export type Lang = "en" | "es" | "fr" | "ar" | "zh";

// ─── Translation Dictionary ───────────────────────────────────────────────────
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Sidebar menu labels
    "menu.overview": "Overview",
    "menu.command_center": "Command Center",
    "menu.crowd_intelligence": "Crowd Intelligence",
    "menu.ai_concierge": "AI Concierge",
    "menu.navigation": "Navigation & Maps",
    "menu.accessibility": "Accessibility",
    "menu.transportation": "Transportation",
    "menu.sustainability": "Sustainability",
    "menu.volunteers": "Volunteers / Staff",
    "menu.incidents": "Incidents & Alerts",
    "menu.analytics": "Reports & Analytics",
    "menu.settings": "Settings",
    // Header titles
    "header.overview.title": "Overview Dashboard",
    "header.overview.sub": "Real-time overview of all venues and operations",
    "header.command_center.title": "Operations Command Center",
    "header.command_center.sub": "Live situation management and incident response",
    "header.crowd_intelligence.title": "Crowd Intelligence",
    "header.crowd_intelligence.sub": "CV people-counting feeds and predictive surge mapping",
    "header.ai_concierge.title": "AI Concierge Assistant",
    "header.ai_concierge.sub": "Multilingual fan chatbot and RAG knowledge lookup",
    "header.navigation.title": "Navigation & Wayfinding",
    "header.navigation.sub": "Crowd-aware stadium routing and PWD accessible guides",
    "header.accessibility.title": "Accessibility Coordinator",
    "header.accessibility.sub": "WD request triage and volunteer escort dispatch queue",
    "header.transportation.title": "Transportation & Parking",
    "header.transportation.sub": "Multimodal transit board and departure optimization planner",
    "header.sustainability.title": "Sustainability & ESG",
    "header.sustainability.sub": "Smart grids, recycling tracking, and anomaly advisory",
    "header.volunteers.title": "Volunteers / Staff",
    "header.volunteers.sub": "Mobile volunteer station shift logs and translation assistant",
    "header.incidents.title": "Incidents & Alerts",
    "header.incidents.sub": "Alert approvals queue and emergency broadcasting logs",
    "header.analytics.title": "Reports & Analytics",
    "header.analytics.sub": "Long-term KPI reporting and tournament operations audit",
    "header.settings.title": "System Settings",
    "header.settings.sub": "Adjust confidence thresholds, model preferences, and API rates",
    // Mode switcher
    "mode.label": "MODE",
    "mode.director": "Director",
    "mode.volunteer": "Volunteer",
    "mode.fan": "Fan",
    // Header UI
    "search.placeholder": "Search...",
    "search.no_results": "No results found",
    "search.hint": "Press Esc to close",
    // Navigation Wayfinding
    "nav.title": "Dynamic Wayfinding & Navigation",
    "nav.subtitle": "Crowd-aware routing with step-by-step PWD accessible paths and AR guidance support.",
    "nav.accessible_on": "Accessible Route: ON",
    "nav.accessible_off": "Accessible Route: OFF",
    "nav.ar_view": "AR View Overlay",
    "nav.gps_active": "GPS Active: Concourse Blue 2",
    "nav.drag_hint": "Drag to orbit · Scroll to zoom",
    "nav.turn_by_turn": "Turn-by-Turn Route",
    "nav.recalc_title": "Dynamic Recalculations",
    "nav.recalc_body": "Our navigation model recalculates paths every 15 seconds based on active concourse people counts. If standard route segments exceed 75% density, the path wraps around alternative walkways automatically.",
    "nav.controls_title": "3-D Viewer Controls",
    "nav.ctrl_drag": "Left-drag",
    "nav.ctrl_drag_desc": "Orbit around stadium",
    "nav.ctrl_scroll": "Scroll",
    "nav.ctrl_scroll_desc": "Zoom in / out",
    "nav.ctrl_accessible": "Accessible",
    "nav.ctrl_accessible_desc": "Gold route ring overlay",
    "nav.step_enter": "Enter through",
    "nav.step_turn_left": "Turn LEFT toward Concourse West",
    "nav.step_turn_right": "Turn RIGHT toward Concourse East",
    "nav.step_reroute": "Rerouting active to avoid high crowd density at",
    "nav.step_route_clear": "Route is clear with normal crowd density.",
    "nav.step_elevator": "Locate elevator at Elevator Plaza",
    "nav.step_stairs": "Take Stairs up to Level 2",
    "nav.step_elevator_desc": "Press 2 for wheelchair platform access.",
    "nav.step_stairs_desc": "Follow signage for Section 102 entry portal.",
    "nav.step_arrive": "Arrive at",
    "nav.step_arrive_desc": "Your seat is located on the left aisle. Have a great match!",
    "nav.step_enter_desc": "Present your digital ticket barcode at the turnstile scanner terminals.",
    "nav.congestion": "Crowd bottleneck at",
    "nav.rerouting": "AI Rerouting active…",
    "nav.ar_sim": "AR VIEWPORT SIMULATION",
    "nav.anchors": "Anchors Locked",
    "nav.concourse_ring": "Concourse Ring",
    "nav.back": "Back",
    "nav.next": "Next",
    "nav.sec102": "Section 102 Row G",
    "nav.seat_desc": "Your seat is on the left aisle. Have a great match!",
  },

  es: {
    "menu.overview": "Resumen",
    "menu.command_center": "Centro de Mando",
    "menu.crowd_intelligence": "Inteligencia de Multitudes",
    "menu.ai_concierge": "Conserjería IA",
    "menu.navigation": "Navegación y Mapas",
    "menu.accessibility": "Accesibilidad",
    "menu.transportation": "Transporte",
    "menu.sustainability": "Sostenibilidad",
    "menu.volunteers": "Voluntarios / Personal",
    "menu.incidents": "Incidentes y Alertas",
    "menu.analytics": "Informes y Análisis",
    "menu.settings": "Configuración",
    "header.overview.title": "Panel de Resumen",
    "header.overview.sub": "Resumen en tiempo real de todos los recintos y operaciones",
    "header.command_center.title": "Centro de Mando Operativo",
    "header.command_center.sub": "Gestión de situaciones en vivo y respuesta a incidentes",
    "header.crowd_intelligence.title": "Inteligencia de Multitudes",
    "header.crowd_intelligence.sub": "Feeds de conteo de personas y mapeo predictivo",
    "header.ai_concierge.title": "Asistente Conserjería IA",
    "header.ai_concierge.sub": "Chatbot multilingüe para aficionados y búsqueda de conocimiento",
    "header.navigation.title": "Navegación y Orientación",
    "header.navigation.sub": "Rutas inteligentes en estadio y guías accesibles para PWD",
    "header.accessibility.title": "Coordinador de Accesibilidad",
    "header.accessibility.sub": "Triaje de solicitudes y cola de escolta de voluntarios",
    "header.transportation.title": "Transporte y Estacionamiento",
    "header.transportation.sub": "Tablero de tránsito multimodal y optimización de salidas",
    "header.sustainability.title": "Sostenibilidad y ESG",
    "header.sustainability.sub": "Redes inteligentes, seguimiento de reciclaje y asesoría",
    "header.volunteers.title": "Voluntarios / Personal",
    "header.volunteers.sub": "Registros de turnos y asistente de traducción",
    "header.incidents.title": "Incidentes y Alertas",
    "header.incidents.sub": "Cola de aprobaciones y registros de transmisión de emergencia",
    "header.analytics.title": "Informes y Análisis",
    "header.analytics.sub": "Informes de KPI a largo plazo y auditoría de operaciones",
    "header.settings.title": "Configuración del Sistema",
    "header.settings.sub": "Ajustar umbrales de confianza y preferencias de modelo",
    "mode.label": "MODO",
    "mode.director": "Director",
    "mode.volunteer": "Voluntario",
    "mode.fan": "Aficionado",
    "search.placeholder": "Buscar...",
    "search.no_results": "Sin resultados",
    "search.hint": "Esc para cerrar",
    "nav.title": "Orientación y Navegación Dinámica",
    "nav.subtitle": "Rutas con reconocimiento de multitudes y guías accesibles para PWD.",
    "nav.accessible_on": "Ruta Accesible: SÍ",
    "nav.accessible_off": "Ruta Accesible: NO",
    "nav.ar_view": "Vista AR",
    "nav.gps_active": "GPS Activo: Corredor Azul 2",
    "nav.drag_hint": "Arrastra para orbitar · Desplaza para zoom",
    "nav.turn_by_turn": "Ruta Paso a Paso",
    "nav.recalc_title": "Recálculos Dinámicos",
    "nav.recalc_body": "El modelo recalcula las rutas cada 15 segundos. Si los segmentos superan el 75% de densidad, la ruta se desvía automáticamente.",
    "nav.controls_title": "Controles del Visor 3D",
    "nav.ctrl_drag": "Arrastrar",
    "nav.ctrl_drag_desc": "Orbitar el estadio",
    "nav.ctrl_scroll": "Desplazar",
    "nav.ctrl_scroll_desc": "Acercar / Alejar",
    "nav.ctrl_accessible": "Accesible",
    "nav.ctrl_accessible_desc": "Anillo de ruta dorada",
    "nav.step_enter": "Entrar por",
    "nav.step_turn_left": "Girar a la IZQUIERDA hacia la Galería Oeste",
    "nav.step_turn_right": "Girar a la DERECHA hacia la Galería Este",
    "nav.step_reroute": "Redireccionando para evitar alta densidad en",
    "nav.step_route_clear": "Ruta despejada con densidad normal.",
    "nav.step_elevator": "Localizar ascensor en Plaza del Elevador",
    "nav.step_stairs": "Subir escaleras al Nivel 2",
    "nav.step_elevator_desc": "Presione 2 para acceso en silla de ruedas.",
    "nav.step_stairs_desc": "Siga los carteles hacia la Sección 102.",
    "nav.step_arrive": "Llegar a",
    "nav.step_arrive_desc": "Tu asiento está en el pasillo izquierdo. ¡Disfruta el partido!",
    "nav.step_enter_desc": "Presenta el código de barras de tu entrada digital en el torniquete.",
    "nav.congestion": "Embotellamiento en",
    "nav.rerouting": "IA redireccionando…",
    "nav.ar_sim": "SIMULACIÓN DE VISOR AR",
    "nav.anchors": "Anclajes Bloqueados",
    "nav.concourse_ring": "Anillo del Pasillo",
    "nav.back": "Atrás",
    "nav.next": "Siguiente",
    "nav.sec102": "Sección 102 Fila G",
    "nav.seat_desc": "Tu asiento está en el pasillo izquierdo. ¡Buen partido!",
  },

  fr: {
    "menu.overview": "Vue d'ensemble",
    "menu.command_center": "Centre de Commandement",
    "menu.crowd_intelligence": "Intelligence des Foules",
    "menu.ai_concierge": "Concierge IA",
    "menu.navigation": "Navigation & Cartes",
    "menu.accessibility": "Accessibilité",
    "menu.transportation": "Transport",
    "menu.sustainability": "Durabilité",
    "menu.volunteers": "Bénévoles / Personnel",
    "menu.incidents": "Incidents & Alertes",
    "menu.analytics": "Rapports & Analyses",
    "menu.settings": "Paramètres",
    "header.overview.title": "Tableau de bord général",
    "header.overview.sub": "Vue en temps réel de tous les sites et opérations",
    "header.command_center.title": "Centre de Commandement Opérationnel",
    "header.command_center.sub": "Gestion des situations en direct et réponse aux incidents",
    "header.crowd_intelligence.title": "Intelligence des Foules",
    "header.crowd_intelligence.sub": "Flux de comptage et cartographie prédictive",
    "header.ai_concierge.title": "Assistant Concierge IA",
    "header.ai_concierge.sub": "Chatbot multilingue et recherche de connaissances RAG",
    "header.navigation.title": "Navigation & Orientation",
    "header.navigation.sub": "Routage intelligent en stade et guides PMR",
    "header.accessibility.title": "Coordinateur Accessibilité",
    "header.accessibility.sub": "Triage des demandes et file d'escorte bénévole",
    "header.transportation.title": "Transport & Stationnement",
    "header.transportation.sub": "Tableau de transit multimodal et optimisation des départs",
    "header.sustainability.title": "Durabilité & ESG",
    "header.sustainability.sub": "Réseaux intelligents, suivi du recyclage et conseils",
    "header.volunteers.title": "Bénévoles / Personnel",
    "header.volunteers.sub": "Journaux de quarts et assistant de traduction",
    "header.incidents.title": "Incidents & Alertes",
    "header.incidents.sub": "File d'approbations et journaux de diffusion d'urgence",
    "header.analytics.title": "Rapports & Analyses",
    "header.analytics.sub": "Rapports KPI à long terme et audit des opérations",
    "header.settings.title": "Paramètres Système",
    "header.settings.sub": "Ajuster les seuils de confiance et les préférences de modèle",
    "mode.label": "MODE",
    "mode.director": "Directeur",
    "mode.volunteer": "Bénévole",
    "mode.fan": "Fan",
    "search.placeholder": "Rechercher...",
    "search.no_results": "Aucun résultat",
    "search.hint": "Échap pour fermer",
    "nav.title": "Orientation & Navigation Dynamique",
    "nav.subtitle": "Routage intelligent avec guides accessibles PMR et guidage AR.",
    "nav.accessible_on": "Itinéraire Accessible : OUI",
    "nav.accessible_off": "Itinéraire Accessible : NON",
    "nav.ar_view": "Vue Superposée AR",
    "nav.gps_active": "GPS Actif : Concourse Bleu 2",
    "nav.drag_hint": "Glisser pour orbiter · Défiler pour zoomer",
    "nav.turn_by_turn": "Itinéraire Étape par Étape",
    "nav.recalc_title": "Recalculs Dynamiques",
    "nav.recalc_body": "Le modèle recalcule les itinéraires toutes les 15 secondes. Si les segments dépassent 75% de densité, le chemin est redirigé automatiquement.",
    "nav.controls_title": "Contrôles du Visualiseur 3D",
    "nav.ctrl_drag": "Glisser",
    "nav.ctrl_drag_desc": "Orbiter autour du stade",
    "nav.ctrl_scroll": "Défiler",
    "nav.ctrl_scroll_desc": "Zoom avant / arrière",
    "nav.ctrl_accessible": "Accessible",
    "nav.ctrl_accessible_desc": "Anneau de route dorée",
    "nav.step_enter": "Entrer par",
    "nav.step_turn_left": "Tourner à GAUCHE vers le Concourse Ouest",
    "nav.step_turn_right": "Tourner à DROITE vers le Concourse Est",
    "nav.step_reroute": "Redirection active pour éviter la haute densité en",
    "nav.step_route_clear": "Itinéraire dégagé avec densité normale.",
    "nav.step_elevator": "Localiser l'ascenseur à la Plaza Ascenseur",
    "nav.step_stairs": "Monter les escaliers au Niveau 2",
    "nav.step_elevator_desc": "Appuyez sur 2 pour l'accès fauteuil roulant.",
    "nav.step_stairs_desc": "Suivez les panneaux vers la Section 102.",
    "nav.step_arrive": "Arriver à",
    "nav.step_arrive_desc": "Votre siège est dans l'allée gauche. Bon match !",
    "nav.step_enter_desc": "Présentez le code-barres de votre billet numérique au tourniquet.",
    "nav.congestion": "Embouteillage en",
    "nav.rerouting": "IA redirige…",
    "nav.ar_sim": "SIMULATION VISEUR AR",
    "nav.anchors": "Ancrages Verrouillés",
    "nav.concourse_ring": "Anneau du Concourse",
    "nav.back": "Retour",
    "nav.next": "Suivant",
    "nav.sec102": "Section 102 Rangée G",
    "nav.seat_desc": "Votre siège est dans l'allée gauche. Bon match !",
  },

  ar: {
    "menu.overview": "نظرة عامة",
    "menu.command_center": "مركز القيادة",
    "menu.crowd_intelligence": "ذكاء الحشود",
    "menu.ai_concierge": "مساعد الذكاء الاصطناعي",
    "menu.navigation": "الملاحة والخرائط",
    "menu.accessibility": "إمكانية الوصول",
    "menu.transportation": "النقل",
    "menu.sustainability": "الاستدامة",
    "menu.volunteers": "المتطوعون / الموظفون",
    "menu.incidents": "الحوادث والتنبيهات",
    "menu.analytics": "التقارير والتحليلات",
    "menu.settings": "الإعدادات",
    "header.overview.title": "لوحة تحكم عامة",
    "header.overview.sub": "نظرة عامة في الوقت الفعلي على جميع المواقع والعمليات",
    "header.command_center.title": "مركز العمليات القيادي",
    "header.command_center.sub": "إدارة المواقف المباشرة والاستجابة للحوادث",
    "header.crowd_intelligence.title": "ذكاء الحشود",
    "header.crowd_intelligence.sub": "تغذية عدد الأشخاص ورسم الخرائط التنبؤية",
    "header.ai_concierge.title": "مساعد الكونسيرج الذكي",
    "header.ai_concierge.sub": "روبوت محادثة متعدد اللغات وبحث المعرفة",
    "header.navigation.title": "الملاحة والتوجيه",
    "header.navigation.sub": "توجيه ذكي في الملعب ومسارات PWD",
    "header.accessibility.title": "منسق إمكانية الوصول",
    "header.accessibility.sub": "فرز الطلبات وطابور مرافقة المتطوعين",
    "header.transportation.title": "النقل والمواقف",
    "header.transportation.sub": "لوحة عبور متعددة الوسائط وتحسين المغادرة",
    "header.sustainability.title": "الاستدامة وESG",
    "header.sustainability.sub": "الشبكات الذكية وتتبع إعادة التدوير والمشورة",
    "header.volunteers.title": "المتطوعون / الموظفون",
    "header.volunteers.sub": "سجلات وردية المحطة ومساعد الترجمة",
    "header.incidents.title": "الحوادث والتنبيهات",
    "header.incidents.sub": "طابور الموافقات وسجلات البث الطارئ",
    "header.analytics.title": "التقارير والتحليلات",
    "header.analytics.sub": "تقارير KPI طويلة الأمد وتدقيق عمليات البطولة",
    "header.settings.title": "إعدادات النظام",
    "header.settings.sub": "ضبط عتبات الثقة وتفضيلات النموذج",
    "mode.label": "الوضع",
    "mode.director": "مدير",
    "mode.volunteer": "متطوع",
    "mode.fan": "مشجع",
    "search.placeholder": "بحث...",
    "search.no_results": "لا توجد نتائج",
    "search.hint": "Esc للإغلاق",
    "nav.title": "التوجيه والملاحة الديناميكية",
    "nav.subtitle": "توجيه يراعي الحشود مع مسارات PWD يدعم AR.",
    "nav.accessible_on": "المسار المتاح: مفعّل",
    "nav.accessible_off": "المسار المتاح: معطّل",
    "nav.ar_view": "عرض AR",
    "nav.gps_active": "GPS نشط: الممشى الأزرق 2",
    "nav.drag_hint": "اسحب للتدوير · مرّر للتكبير",
    "nav.turn_by_turn": "الاتجاه خطوة بخطوة",
    "nav.recalc_title": "إعادة الحسابات الديناميكية",
    "nav.recalc_body": "يعيد النموذج حساب المسارات كل 15 ثانية. إذا تجاوزت الكثافة 75%، يتم إعادة توجيه المسار تلقائياً.",
    "nav.controls_title": "أدوات التحكم في المشاهد ثلاثي الأبعاد",
    "nav.ctrl_drag": "سحب",
    "nav.ctrl_drag_desc": "التدوير حول الملعب",
    "nav.ctrl_scroll": "التمرير",
    "nav.ctrl_scroll_desc": "تكبير / تصغير",
    "nav.ctrl_accessible": "متاح",
    "nav.ctrl_accessible_desc": "حلقة المسار الذهبية",
    "nav.step_enter": "الدخول من",
    "nav.step_turn_left": "انعطف يساراً نحو الممشى الغربي",
    "nav.step_turn_right": "انعطف يميناً نحو الممشى الشرقي",
    "nav.step_reroute": "إعادة التوجيه لتجنب الكثافة العالية في",
    "nav.step_route_clear": "المسار واضح بكثافة طبيعية.",
    "nav.step_elevator": "ابحث عن المصعد في ساحة المصعد",
    "nav.step_stairs": "اصعد الدرج إلى المستوى 2",
    "nav.step_elevator_desc": "اضغط 2 للوصول بالكرسي المتحرك.",
    "nav.step_stairs_desc": "اتبع اللافتات نحو القسم 102.",
    "nav.step_arrive": "الوصول إلى",
    "nav.step_arrive_desc": "مقعدك في الممر الأيسر. استمتع بالمباراة!",
    "nav.step_enter_desc": "قدّم باركود تذكرتك الرقمية عند بوابة الدوران.",
    "nav.congestion": "اختناق مروري في",
    "nav.rerouting": "الذكاء الاصطناعي يعيد التوجيه…",
    "nav.ar_sim": "محاكاة منظور AR",
    "nav.anchors": "المراسي مقفلة",
    "nav.concourse_ring": "حلقة الممشى",
    "nav.back": "رجوع",
    "nav.next": "التالي",
    "nav.sec102": "القسم 102 الصف G",
    "nav.seat_desc": "مقعدك في الممر الأيسر. استمتع بالمباراة!",
  },

  zh: {
    "menu.overview": "总览",
    "menu.command_center": "指挥中心",
    "menu.crowd_intelligence": "人群智能",
    "menu.ai_concierge": "AI礼宾服务",
    "menu.navigation": "导航与地图",
    "menu.accessibility": "无障碍服务",
    "menu.transportation": "交通运输",
    "menu.sustainability": "可持续发展",
    "menu.volunteers": "志愿者/工作人员",
    "menu.incidents": "事件与警报",
    "menu.analytics": "报告与分析",
    "menu.settings": "系统设置",
    "header.overview.title": "总览仪表板",
    "header.overview.sub": "所有场馆和运营的实时总览",
    "header.command_center.title": "运营指挥中心",
    "header.command_center.sub": "实时情况管理和事件响应",
    "header.crowd_intelligence.title": "人群智能",
    "header.crowd_intelligence.sub": "CV人群计数和预测性激增映射",
    "header.ai_concierge.title": "AI礼宾助手",
    "header.ai_concierge.sub": "多语言球迷聊天机器人和RAG知识检索",
    "header.navigation.title": "导航与引导",
    "header.navigation.sub": "人群感知路由和PWD无障碍指南",
    "header.accessibility.title": "无障碍协调员",
    "header.accessibility.sub": "请求分诊和志愿者护送派遣队列",
    "header.transportation.title": "交通与停车",
    "header.transportation.sub": "多模式交通板和出发优化计划",
    "header.sustainability.title": "可持续发展与ESG",
    "header.sustainability.sub": "智能电网、回收跟踪和异常建议",
    "header.volunteers.title": "志愿者/工作人员",
    "header.volunteers.sub": "移动志愿者站轮班日志和翻译助手",
    "header.incidents.title": "事件与警报",
    "header.incidents.sub": "警报审批队列和紧急广播日志",
    "header.analytics.title": "报告与分析",
    "header.analytics.sub": "长期KPI报告和赛事运营审计",
    "header.settings.title": "系统设置",
    "header.settings.sub": "调整置信度阈值、模型偏好和API频率",
    "mode.label": "模式",
    "mode.director": "总监",
    "mode.volunteer": "志愿者",
    "mode.fan": "球迷",
    "search.placeholder": "搜索...",
    "search.no_results": "无结果",
    "search.hint": "按Esc关闭",
    "nav.title": "动态导引与导航",
    "nav.subtitle": "人群感知路由，支持PWD无障碍路径和AR引导。",
    "nav.accessible_on": "无障碍路线：开启",
    "nav.accessible_off": "无障碍路线：关闭",
    "nav.ar_view": "AR叠加视图",
    "nav.gps_active": "GPS激活：蓝色通道2",
    "nav.drag_hint": "拖拽旋转 · 滚轮缩放",
    "nav.turn_by_turn": "逐步路线",
    "nav.recalc_title": "动态重新计算",
    "nav.recalc_body": "导航模型每15秒根据通道人数重新计算路径。若密度超过75%，路径将自动绕行。",
    "nav.controls_title": "3D查看器控件",
    "nav.ctrl_drag": "左键拖拽",
    "nav.ctrl_drag_desc": "围绕场馆旋转",
    "nav.ctrl_scroll": "滚动",
    "nav.ctrl_scroll_desc": "放大 / 缩小",
    "nav.ctrl_accessible": "无障碍",
    "nav.ctrl_accessible_desc": "金色路线环叠加",
    "nav.step_enter": "通过…入场",
    "nav.step_turn_left": "向左转前往西侧通道",
    "nav.step_turn_right": "向右转前往东侧通道",
    "nav.step_reroute": "正在重新路由以避开拥堵区域",
    "nav.step_route_clear": "路线畅通，人群密度正常。",
    "nav.step_elevator": "前往电梯广场找到电梯",
    "nav.step_stairs": "乘楼梯前往2层",
    "nav.step_elevator_desc": "按2以获得轮椅平台通道。",
    "nav.step_stairs_desc": "按标牌前往102区入口。",
    "nav.step_arrive": "到达",
    "nav.step_arrive_desc": "您的座位在左侧过道。祝观赛愉快！",
    "nav.step_enter_desc": "在闸机扫描仪上出示您的数字票条码。",
    "nav.congestion": "拥堵点在",
    "nav.rerouting": "AI正在重新路由…",
    "nav.ar_sim": "AR视口模拟",
    "nav.anchors": "锚点已锁定",
    "nav.concourse_ring": "通道环",
    "nav.back": "返回",
    "nav.next": "下一步",
    "nav.sec102": "102区G排",
    "nav.seat_desc": "您的座位在左侧过道。祝观赛愉快！",
  },
};

// ─── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  isRTL: false,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>("en");

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    document.documentElement.setAttribute("dir", l === "ar" ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", l);
  }, []);

  const t = useCallback(
    (key: string): string =>
      translations[lang]?.[key] ?? translations["en"]?.[key] ?? key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
